version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html

  - source: test.conf
    destination: /etc/apache2/sites-enabled

permissions:
  - object : /var/www/html/codedeploy
    pattern : "*.sh"
    owner : root
    group : root
    mode : 755
    type :
      - file
hooks:
  AfterInstall:
    - location: codedeploy/after_install.sh
      timeout: 90
  ApplicationStart:
    - location: codedeploy/app_start.sh
      timeout: 20
